apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: frontend-mu-deploy
  name: frontend-mu-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-mu-deploy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: frontend-mu-deploy
    spec:
      containers:
        - image: registry.alexbissessur.dev/frontendmu
          name: frontendmu
          resources: {}
          ports:
            - containerPort: 3000

      imagePullSecrets:
        - name: regcred
status: {}
