apiVersion: v1
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJyZWdpc3RyeS5hbGV4Ymlzc2Vzc3VyLmRldiI6IHsKCQkJImF1dGgiOiAiWVd4bGVEcHpZVzVrWld4d2FEazIiCgkJfSwKCQkicmVnaXN0cnkuYWxleGJpc3Nlc3N1ci5kZXY6NTAwMCI6IHsKCQkJImF1dGgiOiAiWVd4bGVEcHpZVzVrWld4d2FEazIiCgkJfQoJfQp9
kind: Secret
metadata:
  creationTimestamp: null
  name: regcred
type: kubernetes.io/dockerconfigjson
