apiVersion: v1
kind: Service
metadata:
  name: frontend-mu-service
  labels:
    app: frontend-mu-deploy
spec:
  selector:
    app: frontend-mu-deploy
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: NodePort
